listening-port=3478
tls-listening-port=5349
realm=example.com
server-name=remote-support-turn
fingerprint
user=turnuser:turnpassword
no-loopback-peers
no-multicast-peers
min-port=49160
max-port=49200
# Uncomment to enable TLS certs
# cert=/etc/ssl/certs/fullchain.pem
# pkey=/etc/ssl/private/privkey.pem
